package com.onai.expressionevaluator.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LoanRateHistory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long id;

	private java.time.LocalDate startDate;

	private java.time.LocalDate endDate;

	private BigDecimal rateOfInterest;

	private BigDecimal totalAmountPaid;

	private BigDecimal totalDays;

	public LoanRateHistory() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public java.time.LocalDate getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.time.LocalDate startDate) {
		this.startDate = startDate;
	}

	public java.time.LocalDate getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.time.LocalDate endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getRateOfInterest() {
		return rateOfInterest;
	}

	public void setRateOfInterest(BigDecimal rateOfInterest) {
		this.rateOfInterest = rateOfInterest;
	}

	public BigDecimal getTotalAmountPaid() {
		return totalAmountPaid;
	}

	public void setTotalAmountPaid(BigDecimal totalAmountPaid) {
		this.totalAmountPaid = totalAmountPaid;
	}

	public BigDecimal getTotalDays() {
		return totalDays;
	}

	public void setTotalDays(BigDecimal totalDays) {
		this.totalDays = totalDays;
	}

	public LoanRateHistory(Long id, java.time.LocalDate startDate,
						   java.time.LocalDate endDate, BigDecimal rateOfInterest,
						   BigDecimal totalAmountPaid, BigDecimal totalDays) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.rateOfInterest = rateOfInterest;
		this.totalAmountPaid = totalAmountPaid;
		this.totalDays = totalDays;
	}

}