package com.onai.expressionevaluator.model;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.math.BigDecimal;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Prepayment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long id;

	private BigDecimal totalInterest;

	private BigDecimal amount;

	private Integer noOfMonths;

	private Double daysToTerminate;

	private BigDecimal totalFee;

	private String paymentType;

	private List<LoanRateHistory> loanRateHistoryList;

	private Double calculateTotalFee;

	private String feeCalculationFormula;

	private BigDecimal flatInterest;

	private List<BigDecimal> actualInterestPaid;

	private java.time.LocalDate periodStartDate;

	private java.time.LocalDate periodEndDate;

	private String regularExpression;

	private String objectName;

	public Prepayment() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getNoOfMonths() {
		return this.noOfMonths;
	}

	public void setNoOfMonths(Integer noOfMonths) {
		this.noOfMonths = noOfMonths;
	}

	public BigDecimal getTotalInterest() {
		return totalInterest;
	}

	public void setTotalInterest(BigDecimal totalInterest) {
		this.totalInterest = totalInterest;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Double getDaysToTerminate() {
		return this.daysToTerminate;
	}

	public void setDaysToTerminate(Double daysToTerminate) {
		this.daysToTerminate = daysToTerminate;
	}

	public BigDecimal getTotalFee() {
		return totalFee;
	}

	public void setTotalFee(BigDecimal totalFee) {
		this.totalFee = totalFee;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public List<LoanRateHistory> getLoanRateHistoryList() {
		return this.loanRateHistoryList;
	}

	public void setLoanRateHistoryList(
			List<LoanRateHistory> loanRateHistoryList) {
		this.loanRateHistoryList = loanRateHistoryList;
	}

	public String getFeeCalculationFormula() {
		return this.feeCalculationFormula;
	}

	public void setFeeCalculationFormula(String feeCalculationFormula) {
		this.feeCalculationFormula = feeCalculationFormula;
	}

	public Double getCalculateTotalFee() {
		return this.calculateTotalFee;
	}

	public void setCalculateTotalFee(Double calculateTotalFee) {
		this.calculateTotalFee = calculateTotalFee;
	}

	public BigDecimal getFlatInterest() {
		return flatInterest;
	}

	public void setFlatInterest(BigDecimal flatInterest) {
		this.flatInterest = flatInterest;
	}

	public List<BigDecimal> getActualInterestPaid() {
		return actualInterestPaid;
	}

	public void setActualInterestPaid(List<BigDecimal> actualInterestPaid) {
		this.actualInterestPaid = actualInterestPaid;
	}

	public java.time.LocalDate getPeriodStartDate() {
		return this.periodStartDate;
	}

	public void setPeriodStartDate(java.time.LocalDate periodStartDate) {
		this.periodStartDate = periodStartDate;
	}

	public java.time.LocalDate getPeriodEndDate() {
		return this.periodEndDate;
	}

	public void setPeriodEndDate(java.time.LocalDate periodEndDate) {
		this.periodEndDate = periodEndDate;
	}

	public String getRegularExpression() {
		return regularExpression;
	}

	public String getObjectName() {
		return objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public void setRegularExpression(String regularExpression) {
		this.regularExpression = regularExpression;
	}

	public Prepayment(Long id, BigDecimal totalInterest,
					  BigDecimal amount, Integer noOfMonths,
					  Double daysToTerminate, BigDecimal totalFee,
					  String paymentType,
					  List<LoanRateHistory> loanRateHistoryList,
					  Double calculateTotalFee,
					  String feeCalculationFormula,
					  BigDecimal flatInterest,
					  List<BigDecimal> actualInterestPaid,
					  java.time.LocalDate periodStartDate,
					  java.time.LocalDate periodEndDate) {
		this.id = id;
		this.totalInterest = totalInterest;
		this.amount = amount;
		this.noOfMonths = noOfMonths;
		this.daysToTerminate = daysToTerminate;
		this.totalFee = totalFee;
		this.paymentType = paymentType;
		this.loanRateHistoryList = loanRateHistoryList;
		this.calculateTotalFee = calculateTotalFee;
		this.feeCalculationFormula = feeCalculationFormula;
		this.flatInterest = flatInterest;
		this.actualInterestPaid = actualInterestPaid;
		this.periodStartDate = periodStartDate;
		this.periodEndDate = periodEndDate;
	}

}