package com.onai.expressionevaluator.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RatioValue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long id;

	private String financialYear;

	private double data;

	private int absoluteAnomaly;

	private String ratioName;

	private double slope;

	public RatioValue() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFinancialYear() {
		return this.financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}

	public double getData() {
		return this.data;
	}

	public void setData(double data) {
		this.data = data;
	}

	public int getAbsoluteAnomaly() {
		return this.absoluteAnomaly;
	}

	public void setAbsoluteAnomaly(int absoluteAnomaly) {
		this.absoluteAnomaly = absoluteAnomaly;
	}

	public String getRatioName() {
		return this.ratioName;
	}

	public void setRatioName(String ratioName) {
		this.ratioName = ratioName;
	}

	public double getSlope() {
		return this.slope;
	}

	public void setSlope(double slope) {
		this.slope = slope;
	}

	public RatioValue(Long id, String financialYear,
                      double data, int absoluteAnomaly, String ratioName,
                      double slope) {
		this.id = id;
		this.financialYear = financialYear;
		this.data = data;
		this.absoluteAnomaly = absoluteAnomaly;
		this.ratioName = ratioName;
		this.slope = slope;
	}

}