package com.onai.expressionevaluator.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Record implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long id;

	private int companyId;

	private int borrowerId;

	private int loanId;

	private String dataVersion;

	private String measurementType;

	private String ratioName;

	private String trend;

	private java.util.List<Integer> anomaly;

	private int absoluteMajorityAnomaly;

	private java.util.List<RatioValue> ratioValues;

	public Record() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public int getBorrowerId() {
		return this.borrowerId;
	}

	public void setBorrowerId(int borrowerId) {
		this.borrowerId = borrowerId;
	}

	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	public String getDataVersion() {
		return this.dataVersion;
	}

	public void setDataVersion(String dataVersion) {
		this.dataVersion = dataVersion;
	}

	public String getMeasurementType() {
		return this.measurementType;
	}

	public void setMeasurementType(String measurementType) {
		this.measurementType = measurementType;
	}

	public String getRatioName() {
		return this.ratioName;
	}

	public void setRatioName(String ratioName) {
		this.ratioName = ratioName;
	}

	public String getTrend() {
		return this.trend;
	}

	public void setTrend(String trend) {
		this.trend = trend;
	}

	public java.util.List<Integer> getAnomaly() {
		return this.anomaly;
	}

	public void setAnomaly(java.util.List<Integer> anomaly) {
		this.anomaly = anomaly;
	}

	public int getAbsoluteMajorityAnomaly() {
		return this.absoluteMajorityAnomaly;
	}

	public void setAbsoluteMajorityAnomaly(int absoluteMajorityAnomaly) {
		this.absoluteMajorityAnomaly = absoluteMajorityAnomaly;
	}

	public java.util.List<RatioValue> getRatioValues() {
		return this.ratioValues;
	}

	public void setRatioValues(
			java.util.List<RatioValue> ratioValues) {
		this.ratioValues = ratioValues;
	}

	public Record(Long id, int companyId, int borrowerId, int loanId,
                  String dataVersion, String measurementType,
                  String ratioName, String trend,
                  java.util.List<Integer> anomaly,
                  int absoluteMajorityAnomaly,
                  java.util.List<RatioValue> ratioValues) {
		this.id = id;
		this.companyId = companyId;
		this.borrowerId = borrowerId;
		this.loanId = loanId;
		this.dataVersion = dataVersion;
		this.measurementType = measurementType;
		this.ratioName = ratioName;
		this.trend = trend;
		this.anomaly = anomaly;
		this.absoluteMajorityAnomaly = absoluteMajorityAnomaly;
		this.ratioValues = ratioValues;
	}

}